[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "./editor",
    # "../extend_traits",
]


[dependencies]
yew = "0.19.3"
yew-router = "0.16.0"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4.28"
gloo = "0.8.0"
js-sys = "0.3.59"
serde = "1.0.144"
serde_json = "1.0.85"
serde_derive = "1.0.144"
reqwest = { version = "0.11.11", features = ["json"]}
graphql_client = "0.11.0"
anyhow = "1.0.62"
cfg-if = "1.0.0"
yewdux = "0.8"
futures = "0.3.24"
editor = { path = "editor" }


[dependencies.web-sys]
version = "0.3.56"

features = [
    'Document',
    'Element',
    'HtmlElement',
    'HtmlInputElement',
    'Node',
    'Window',
    "DomParser",
    "SupportedType",
    "NodeList",
    "Event",
    "EventTarget",
    "HtmlFormElement",
    "DomRect",
    "DataTransfer",
    "DragEvent",
    "Storage",
    "Selection",
    "Range",
    "console",
    "DomTokenList", #for class_list
]

[features]

web= []
