server:
	trunk serve --features web

run:
	cargo run

kill:
	kill -INT $(lsof -t -i :8080)

update:
	cargo update


clean:
	rm -rf ~/.cargo/registry/index/*
	rm -rf ~/.cargo/.package-cache
	cargo clean