[workspace]
members = [
    "shared",
    "frontend",
    "tauri-src", # tauri-src is out of the workspace because it works indipdently
    "editor",
    "canisters/backend",
    #    "webscoket_server",
]
