[workspace]
members = [
    "shared",
    "frontend",
    "tauri", # tauri is out of the workspace because it works indipdently
    "editor",
    "tauri/migration",
    "autodox/src/autodox_backend"
]
