[workspace]
members = [
    "shared",
    "frontend",
    "tauri", # tauri is out of the workspace because it works indipdently
    "editor",
    "backend/registrar",
    "backend/storage",

    "webscoket_server",
]
