run:
	cargo tauri dev && cd frontend; npx webpack serve

build:
	cargo tauri build

kill:
	kill -INT $(lsof -t -i :8080)

update:
	cargo update

install_cli:
	cargo install tauri-cli

clean:
	cargo clean

get_principal:
	dfx identity get-principal

create_token:
	dfx canister create token

ddd:
	OWNER_PUBLIC_KEY="principal \"$( \dfx identity get-principal )\""

get_dfx_balance:
	dfx canister call token balance "( $OWNER_PUBLIC_KEY )"


deploy:
	# make sure to run dfx start in order to start the smulated blockchain locally
	# make sure to have Cargo.lock files so the dfx can install from it because dfx does not install from Cargo.toml
	#dfx deploy registrar --with-cycles 10000000000000
	dfx deploy backend
