run:
	cargo tauri dev

build:
	cargo tauri build

kill:
	kill -INT $(lsof -t -i :8080)

update:
	cargo update

install_cli:
	cargo install tauri-cli

clean:
	cargo clean

get_principal:
	dfx identity get-principal

create_token:
	dfx canister create token

ddd:
	OWNER_PUBLIC_KEY="principal \"$( \dfx identity get-principal )\""

get_dfx_balance:
	dfx canister call token balance "( $OWNER_PUBLIC_KEY )"

