//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "file_tree")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub root: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::file_node::Entity",
        from = "Column::Root",
        to = "super::file_node::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FileNode,
    #[sea_orm(has_many = "super::file_adjacency::Entity")]
    FileAdjacency,
}

impl Related<super::file_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileNode.def()
    }
}

impl Related<super::file_adjacency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileAdjacency.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
