//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2


use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::utils::UuidSet;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize, Eq, Default)]
#[sea_orm(table_name = "file_adjacency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tree_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent_id: Uuid,
    pub child_id: UuidSet,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::file_node::Entity",
        from = "Column::ParentId",
        to = "super::file_node::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FileNode,
    #[sea_orm(
        belongs_to = "super::file_tree::Entity",
        from = "Column::TreeId",
        to = "super::file_tree::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FileTree,
}

impl Related<super::file_node::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileNode.def()
    }
}

impl Related<super::file_tree::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileTree.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
 
