//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize, Eq, Default)]
#[sea_orm(table_name = "file_node")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub element_tree_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_adjacency::Entity")]
    FileAdjacency,
    #[sea_orm(has_many = "super::file_tree::Entity")]
    FileTree,
}

impl Related<super::file_adjacency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileAdjacency.def()
    }
}

impl Related<super::file_tree::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileTree.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
