install:
	cargo install ic-cdk-optimizer
	brew install cmake


run:
	cargo run

start:
	dfx start --background
	npm i --background
	dfx deploy --background

deploy:
	dfx deploy

create:
	dfx canister create --all

############################################################ other commands
install_wasm_unknown:
	rustup target add wasm32-unknown-unknown


get_id:
	dfx canister id __Candid_UI

trunk:
	trunk serve --open

##  2. using wasm-pack
pack:
	python -m http.server 8000
	#then go to
	#http://127.0.0.1:8000/??canisterId=<______>

##  3. using cargo-web
web:
	#cargo install cargo-web
	#cargo web build
	cargo web start

kill_all:
	killall dfx replica

optimize:
	ic-cdk-optimizer target/wasm32-unknown-unknown/debug/main.wasm -o target/wasm32-unknown-unknown/debug/main-opt.wasm


npm:
	npm start
