name: test dfx

on:
  push:
    branches: [ "main" ]
  merge:
    branches: [ "main" ]

jobs:
  runs-on: ${{matrix.os}}
  strategy:
    matrix:
      os: [ fedora-latest, windows-latest, macOs-latest ]
  steps:
    - name: build linux version
      run: cargo tauri build --release --features "tauri"