name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#    - uses: mr-smithers-excellent/docker-build-push@v5 # note this must run only on linux?
#      name: Build & push Docker image
#      with:
#        image: moveaxebx/autodox
#        tags: v1, latest
#        registry: registry-url.io
#        dockerfile: Dockerfile.ci
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
